var weatherObj ={
            "last_updated_epoch": 0,
            "last_updated": "",
            "temp_c": 0.0,
            "temp_f": 0.0,
            "is_day": 0,
            "currentCondition": "",
            "icon": "",
            "code": 0,
            "wind_mph": 0.0,
            "wind_kph": 0.0,
            "wind_degree": 0,
            "wind_dir": "",
            "pressure_mb": 0.0,
            "pressure_in": 0.0,
            "precip_mm": 0.0,
            "precip_in": 0.0,
            "humidity": 0,
            "cloud": 0,
            "feelslike_c": 0.0,
            "feelslike_f": 0.0,
            "vis_km": 0.0,
            "vis_miles": 0.0,
            "uv": 0.0,
            "gust_mph": 0.0,
            "gust_kph": 0.0
        }